### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by MasterWolf** [BukkitPE/BungeeCordPE#1]
Hi! Im from BigBrother... Can you help me here?

**Comment by AndreTheGamer** [comment]
Sure, are you running BukkitPE??

**Comment by MasterWolf** [comment]
@AndreTheGamer no

**Comment by MasterWolf** [comment]
@AndreTheGamer i have ClearSky

**Comment by AndreTheGamer** [comment]
As of right now, it only works/have been developed for BukkitPE

**Comment by MasterWolf** [comment]
@AndreTheGamer oh ok... But how it works? How can i connect to mcpe server from pc? If its possible i will install BukkitPE on my server.

**Comment by AndreTheGamer** [comment]
Yes, it will. When BungeeCordPE is finished. But as of now BungeeCordPE will just handle players...ect) But again you should switch to BungeeCordPE if your looking for some cool features ;)

**Comment by MasterWolf** [comment]
ok thx
