### ISSUE TITLE
How to resolve this?

### ISSUE THREAD

**Issue by GabiYT** [BukkitPE/BungeeCordPE#2]
[Server] [17:13:05] [WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [17:13:05] [INFO]: ------> BukkitPE.yml Has been loaded
[Server] [17:13:05] [INFO]: Loading server properties...
[Server] [17:13:05] [INFO]: Selected English (eng) as the base language
[Server] [17:13:05] [INFO]: [Info] Starting BukkitPE version alpha 0.14.0
[Server] [17:13:05] [INFO]: Opening server on 0.0.0.0:19133
[Server] [17:13:05] [INFO]: [Info] ====--> BukkitPE is running BukkitPE version Stable_V2 "1.13.1" (API {%3})
[Server] [17:13:05] [INFO]: BukkitPE is distributed under the LGPL License
[Server] [17:13:07] [ERROR]: [Info] Could not load '/storage/emulated/0/PocketMine/plugins/BungeeCordPE.phar' in folder '/storage/emulated/0/PocketMine/plugins/': Undefined index: main
[Server] [17:13:07] [NOTICE]: ArrayOutOfBoundsException: "Undefined index: main" (E_NOTICE) in "/src/BukkitPE/plugin/PluginDescription" at line 46
[Server] [17:13:07] [INFO]: [Info] Loading BukkitTP v1.0.0
[Server] [17:13:07] [INFO]: [Info] Loading BukkitAuth v1.7.1
[Server] [17:13:07] [INFO]: [Info] Loading DevTools v1.10.0
[Server] [17:13:07] [INFO]: [Info] Loading BukkitBroadcast v1.0.0
[Server] [17:13:07] [INFO]: [Info] Enabling Plugin =====> BukkitAuth v1.7.1
[Server] [17:13:07] [INFO]: [BukkitAuth] Everything loaded!
[Server] [17:13:07] [INFO]: [Info] Enabling Plugin =====> DevTools v1.10.0
[Server] [17:13:07] [INFO]: [DevTools] Registered folder plugin loader
[Server] [17:13:07] [NOTICE]: Level "Hub" not found
[Server] [17:13:07] [INFO]: [Info] Preparing level "Hub"
[Server] [17:13:07] [NOTICE]: [Info] World: "Hub" is being generated in the background
[Server] [17:13:07] [INFO]: [Info] Enabling Plugin =====> BukkitTP v1.0.0
[Server] [17:13:07] [INFO]: [BukkitTP] BukkitTP loading...
[Server] [17:13:07] [INFO]: [BukkitTP] [INFO] loading [config.yml]....
[Server] [17:13:07] [INFO]: [BukkitTP] [INFO] loading [config.yml] DONE
[Server] [17:13:07] [INFO]: [BukkitTP] BukkitTP loaded!
[Server] [17:13:07] [INFO]: [Info] Enabling Plugin =====> BukkitBroadcast v1.0.0
[Server] [17:13:07] [INFO]: [BukkitBroadcast] BukkitBroadcast has been enabled
[Server] [17:13:09] [INFO]: [Info] Starting GS4 status listener
[Server] [17:13:09] [INFO]: [Info] Setting query port to 19133
[Server] [17:13:09] [INFO]: [Info] Query running on 0.0.0.0:19133
[Server] [17:13:09] [INFO]: [Info] Default game type: Survival Mode
[Server] [17:13:09] [INFO]: [Info] Server has been loaded (9.303s)! For help, type "help" or "?"
[Server] [17:13:09] [INFO]: [Broadcaster] Welcome to my server

**Comment by GabiYT** [comment]
BungeeCordPE is not working

**Comment by AndreTheGamer** [comment]
Um, it's still in beta. That must be why

**Comment by DelxHQ** [comment]
@GabiYT BungeeCordPE has not been finished yet. All it does is sends a message to the console when it gets enabled.

**Comment by GabiYT** [comment]
@DelxHQ ok. Thanks
